-- No hardcoded database names! Snowflake will use the active session database.
CREATE SCHEMA IF NOT EXISTS APPLICATION_DATA;

CREATE TABLE IF NOT EXISTS APPLICATION_DATA.USERS (
    ID INT,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
