-- 1. Create an audit schema to log tracking data 
CREATE SCHEMA IF NOT EXISTS LOGGING;

-- 2. Add an environmental audit table
CREATE TABLE IF NOT EXISTS LOGGING.DEPLOYMENT_AUDIT (
    DEPLOYMENT_ID INT IDENTITY(1,1),
    DEPLOYED_BY STRING DEFAULT CURRENT_USER(),
    ENVIRONMENT_NAME STRING DEFAULT CURRENT_DATABASE(),
    EXECUTION_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. Add a new operational column to your existing USERS table
ALTER TABLE APPLICATION_DATA.USERS ADD COLUMN IS_ACTIVE BOOLEAN DEFAULT TRUE;
