CREATE SCHEMA IF NOT EXISTS POC_DEPLOYMENT_DB.APPLICATION_DATA;
CREATE TABLE IF NOT EXISTS POC_DEPLOYMENT_DB.APPLICATION_DATA.USERS (
    ID INT,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
