name: Snowflake Multi-Environment Deploy

on:
  push:
    branches:
      - main
      - 'feature/**'
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  # ----------------------------------------------------
  # DEV STAGE
  # ----------------------------------------------------
  deploy-dev:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          use-oidc: true
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_TOKEN: ${{ env.SNOWFLAKE_TOKEN }}
          SNOWFLAKE_USER: ${{ vars.CICD_USER }}
          SNOWFLAKE_DATABASE: ${{ vars.TARGET_DB }}

      - name: Test Dev Connection
        run: snow connection test -x

      - name: Deploy to Dev
        run: snow sql -f ./scripts/V1.1__setup_tables.sql -x

  # ----------------------------------------------------
  # UAT STAGE
  # ----------------------------------------------------
  deploy-uat:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          use-oidc: true
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_TOKEN: ${{ env.SNOWFLAKE_TOKEN }}
          SNOWFLAKE_USER: ${{ vars.CICD_USER }}
          SNOWFLAKE_DATABASE: ${{ vars.TARGET_DB }}

      - name: Test UAT Connection
        run: snow connection test -x

      - name: Deploy to UAT
        run: snow sql -f ./scripts/V1.1__setup_tables.sql -x

  # ----------------------------------------------------
  # PROD STAGE
  # ----------------------------------------------------
  deploy-prod:
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          use-oidc: true
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_TOKEN: ${{ env.SNOWFLAKE_TOKEN }}
          SNOWFLAKE_USER: ${{ vars.CICD_USER }}
          SNOWFLAKE_DATABASE: ${{ vars.TARGET_DB }}

      - name: Test Prod Connection
        run: snow connection test -x

      - name: Deploy to Prod
        run: snow sql -f ./scripts/V1.1__setup_tables.sql -x
