name: Snowflake Multi-Environment Deploy

on:
  push:
    branches:
      - main
      - 'feature/**'
workflow_dispatch: # <-- Add this line right here!
permissions:
  id-token: write
  contents: read

jobs:
  # ----------------------------------------------------
  # DEV STAGE
  # ----------------------------------------------------
  deploy-dev:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          use-oidc: true
          default-config-file-path: "config.toml"
        env:
          SNOWFLAKE_CONNECTIONS_POC_CONN_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_CONNECTIONS_POC_CONN_TOKEN: ${{ env.SNOWFLAKE_TOKEN }}
          SNOWFLAKE_CONNECTIONS_POC_CONN_USER: ${{ vars.CICD_USER }}       # Native override
          SNOWFLAKE_CONNECTIONS_POC_CONN_DATABASE: ${{ vars.TARGET_DB }}  # Native override

      - name: Deploy to Dev
        run: snow sql -f ./scripts/V1.1__setup_tables.sql

  # ----------------------------------------------------
  # UAT STAGE
  # ----------------------------------------------------
  deploy-uat:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          use-oidc: true
          default-config-file-path: "config.toml"
        env:
          SNOWFLAKE_CONNECTIONS_POC_CONN_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_CONNECTIONS_POC_CONN_TOKEN: ${{ env.SNOWFLAKE_TOKEN }}
          SNOWFLAKE_CONNECTIONS_POC_CONN_USER: ${{ vars.CICD_USER }}       # Native override
          SNOWFLAKE_CONNECTIONS_POC_CONN_DATABASE: ${{ vars.TARGET_DB }}  # Native override

      - name: Deploy to UAT
        run: snow sql -f ./scripts/V1.1__setup_tables.sql

  # ----------------------------------------------------
  # PROD STAGE
  # ----------------------------------------------------
  deploy-prod:
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          use-oidc: true
          default-config-file-path: "config.toml"
        env:
          SNOWFLAKE_CONNECTIONS_POC_CONN_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_CONNECTIONS_POC_CONN_TOKEN: ${{ env.SNOWFLAKE_TOKEN }}
          SNOWFLAKE_CONNECTIONS_POC_CONN_USER: ${{ vars.CICD_USER }}       # Native override
          SNOWFLAKE_CONNECTIONS_POC_CONN_DATABASE: ${{ vars.TARGET_DB }}  # Native override

      - name: Deploy to Prod
        run: snow sql -f ./scripts/V1.1__setup_tables.sql
